### ISSUE TITLE
add_mirror.sh is throwing error 410 with GitLab 11.x

### ISSUE THREAD

**Issue by kadimgh** [samrocketman/gitlab-mirrors#107]
I've been using gitlab-mirrors (master branch) regularly for over a year with GitLab 10.x. Currently I'm on Gitlab 11.1.4 and I'm not able to add new mirrors anymore. When I do so I get:

`
#./add_mirror.sh --git --project-name XXX --mirror XXX
...
Traceback (most recent call last):
  File "lib/manage_gitlab_project.py", line 97, in <module>
    found_group=git.find_group(name=gitlab_namespace)
  File "/usr/local/lib/python2.7/dist-packages/gitlab3/__init__.py", line 150, in fn
    return _find_matches(objects, kwargs, find_all)
  File "/usr/local/lib/python2.7/dist-packages/gitlab3/__init__.py", line 108, in _find_matches
    for obj in objects:
  File "/usr/local/lib/python2.7/dist-packages/gitlab3/__init__.py", line 48, in _query_list
    objs = parent._get(api_cls._uq_url, data=data)
  File "/usr/local/lib/python2.7/dist-packages/gitlab3/__init__.py", line 424, in _get
    return self._request(requests.get, api_url, addl_keys, data)
  File "/usr/local/lib/python2.7/dist-packages/gitlab3/__init__.py", line 447, in _request
    self._check_status_code(r.status_code, url, data)
  File "/usr/local/lib/python2.7/dist-packages/gitlab3/__init__.py", line 420, in _check_status_code
    raise self._code_to_exc[status_code](msg)
KeyError: 410
There was an unknown issue with manage_gitlab_project.py
`

Switching to development branch and using workaround with "v4" described in #106 gives ability to add new mirrors, however it's very obscure (also docs/upgrade/upgrade_0.5.x-0.6.x.md mentions 0.6.x tag but it does not exist yet). If there are no plans to merge development into master anytime soon then can readme.md on the master branch be updated with branch usage as currently master is not working anymore (I believe not only for myself)?

**Comment by samrocketman** [comment]
Try development branch.  Does it still occur?

**Comment by GammaPi** [comment]
Same Problem

**Comment by GammaPi** [comment]
gitmirror@xxx:~/gitlab-mirrors$ ./add_mirror.sh --git --project-name cmusatyalab-openface --mirror https://github.com/cmusatyalab/openface.git
Resolving gitlab remote.
/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
Traceback (most recent call last):
  File "lib/manage_gitlab_project.py", line 131, in <module>
    found_group = find_group(name=gitlab_namespace)
  File "lib/manage_gitlab_project.py", line 53, in find_group
    groups = git.groups.list()
  File "/usr/local/lib/python2.7/dist-packages/gitlab/exceptions.py", line 242, in wrapped_f
    return f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/gitlab/mixins.py", line 133, in list
    obj = self.gitlab.http_list(path, **data)
  File "/usr/local/lib/python2.7/dist-packages/gitlab/__init__.py", line 562, in http_list
    **kwargs))
  File "/usr/local/lib/python2.7/dist-packages/gitlab/__init__.py", line 671, in __init__
    self._query(url, query_data, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/gitlab/__init__.py", line 676, in _query
    **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/gitlab/__init__.py", line 491, in http_request
    response_body=result.content)
gitlab.exceptions.GitlabAuthenticationError: 401: 401 Unauthorized
There was an unknown issue with manage_gitlab_project.py

**Comment by kadimgh** [comment]
@GammaPi your issues is different. You get "401 Unauthorized", so check if you have your authentication configured properly

**Comment by GammaPi** [comment]
Sorry, @kadimgh I didn't double check the error code, but I did meet the same 410 problem like you.
After switching to the development branch and reconfigured according to wiki, all issues are solved!

**Comment by fhaefemeier** [comment]
When will the development branch merged back to master to release a new version? The latest release is no longer working with Gitlab, because api V3 is removed since Gitlab V11.

**Comment by samrocketman** [comment]
I can cut a release today.

**Comment by samrocketman** [comment]
I have released 0.6.0.
