### ISSUE TITLE
./add_mirror.sh error

### ISSUE THREAD

**Issue by jiangby123** [samrocketman/gitlab-mirrors#127]
Resolving gitlab remote.
Traceback (most recent call last):
  File "lib/manage_gitlab_project.py", line 10, in <module>
    import gitlab
  File "/usr/lib/python2.7/site-packages/gitlab/__init__.py", line 612
    ) from e
         ^
SyntaxError: invalid syntax
There was an unknown issue with manage_gitlab_project.py

**Comment by fengzhibin** [comment]
same error

**Comment by fengzhibin** [comment]
Resolving gitlab remote.
Traceback (most recent call last):
  File "lib/manage_gitlab_project.py", line 10, in <module>
    import gitlab
  File "/usr/lib/python2.7/site-packages/gitlab/__init__.py", line 613
    ) from e
         ^
SyntaxError: invalid syntax

**Comment by ydewinte** [comment]
I found out what the issue was.
By checking when the docs were written I found out that they were written at the time python-gitlab was on v1.x.
By doing the following:

```
pip uninstall python-gitlab
pip install python-gitlab==1.15.
```

It started working better:

```
[gitmirror@hylek gitlab-mirrors]$ ./add_mirror.sh --git --project-name github-gitlab-mirrors --mirror https://github.com/samrocketman/gitlab-mirrors.git
Resolving gitlab remote.
Creating new project github-gitlab-mirrors
Creating mirror from https://github.com/samrocketman/gitlab-mirrors.git
Cloning into bare repository 'github-gitlab-mirrors'...
remote: Enumerating objects: 9, done.
remote: Counting objects: 100% (9/9), done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 1292 (delta 1), reused 5 (delta 0), pack-reused 1283
Receiving objects: 100% (1292/1292), 245.63 KiB | 0 bytes/s, done.
Resolving deltas: 100% (678/678), done.
Adding gitlab remote to project.
Checking the mirror into gitlab.
Bad owner or permissions on /home/gitmirror/.ssh/config
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

```
Still figuring out how what is wrong with the next step, but getting closer :)

**Comment by samrocketman** [comment]
@ydewinte thanks for the solution for others.

I think I will touch up this project and simplify it a bit.  I'll pip freeze dependencies and update documentation to recommend use of virtualenv.
