### ISSUE TITLE
requests.exceptions.TooManyRedirects: Exceeded 30 redirects

### ISSUE THREAD

**Issue by exOGit** [samrocketman/gitlab-mirrors#129]
```
./add_mirror.sh --git --project-name Mirror/project_name --mirror http://gitlab.example.com/Group/project

Resolving gitlab remote.
Traceback (most recent call last):
  File "lib/manage_gitlab_project.py", line 131, in <module>
    found_group = find_group(name=gitlab_namespace)
  File "lib/manage_gitlab_project.py", line 53, in find_group
    groups = git.groups.list()
  File "/usr/lib/python2.7/dist-packages/gitlab/exceptions.py", line 246, in wrapped_f
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/gitlab/mixins.py", line 133, in list
    obj = self.gitlab.http_list(path, **data)
  File "/usr/lib/python2.7/dist-packages/gitlab/__init__.py", line 573, in http_list
    **kwargs))
  File "/usr/lib/python2.7/dist-packages/gitlab/__init__.py", line 682, in __init__
    self._query(url, query_data, **kwargs)
  File "/usr/lib/python2.7/dist-packages/gitlab/__init__.py", line 687, in _query
    **kwargs)
  File "/usr/lib/python2.7/dist-packages/gitlab/__init__.py", line 481, in http_request
    result = self.session.send(prepped, timeout=timeout, **settings)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 668, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 165, in resolve_redirects
    raise TooManyRedirects('Exceeded %s redirects.' % self.max_redirects, response=resp)
requests.exceptions.TooManyRedirects: Exceeded 30 redirects.
There was an unknown issue with manage_gitlab_project.py
```

Can anyone help with this ?..
I don't know what's the issue...

**Comment by samrocketman** [comment]
Sounds like a frontend misconfiguration on your GitLab host.  30 redirects is a lot and is likely an infinite loop.
