### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'id'

### ISSUE THREAD

**Issue by sduensin** [samrocketman/gitlab-mirrors#139]
gitmirror@stuff:~/gitlab-mirrors$ ./add_mirror.sh --git --project-name osxcross --mirror https://github.com/tpoechtrager/osxcross
Resolving gitlab remote.
Traceback (most recent call last):
  File "lib/manage_gitlab_project.py", line 149, in <module>
    found_project=createproject(project_name)
  File "lib/manage_gitlab_project.py", line 110, in createproject
    'namespace_id': find_group(name=gitlab_namespace).id,
AttributeError: 'NoneType' object has no attribute 'id'
There was an unknown issue with manage_gitlab_project.py

**Comment by samrocketman** [comment]
This relies on a really old version of python-gitlab [v1.1.0](https://github.com/python-gitlab/python-gitlab).  Are you using the old version or attempting to use the latest version?

The code needs a bit of an overhaul in general as its age is showing.

**Comment by sduensin** [comment]
Thanks for the quick reply.  I have no idea.  I'm using whatever my package manager supplied.  I'll see if I can downgrade to the recommended version.

**Comment by sduensin** [comment]
I purged whatever I had installed with apt and used pip to install 1.1.0.  Same issue.  :-(

**Comment by oldunclez** [comment]
@sduensin  which version do you use ? 

Today , I have setup  it with python2.7 , gitlab-mirrors (main branch) , python-gitlab 1.1.0

**Comment by typuc** [comment]
> gitmirror@stuff:~/gitlab-mirrors$ ./add_mirror.sh --git --project-name osxcross --mirror https://github.com/tpoechtrager/osxcross Resolving gitlab remote. Traceback (most recent call last): File "lib/manage_gitlab_project.py", line 149, in found_project=createproject(project_name) File "lib/manage_gitlab_project.py", line 110, in createproject 'namespace_id': find_group(name=gitlab_namespace).id, AttributeError: 'NoneType' object has no attribute 'id' There was an unknown issue with manage_gitlab_project.py

maybe your group numbers is over default number(10), try  to modify  "lib/manage_gitlab_project.py" add "page=1, per_page=100"
 ```
def find_group(**kwargs):
  groups = git.groups.list(page=1, per_page=100)
  return _find_matches(groups, kwargs, False)

def find_project(**kwargs):
  projects = git.projects.list(as_list=True,page=1, per_page=100)
  return _find_matches(projects, kwargs, False)

```
