### ISSUE TITLE
error  during found_group=findgroup(gitlab_namespace)

### ISSUE THREAD

**Issue by logicminds** [samrocketman/gitlab-mirrors#75]
Using the public gitlab site.

/usr/lib/python2.6/site-packages/requests/packages/urllib3/connectionpool.py:768: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
Traceback (most recent call last):
  File "lib/manage_gitlab_project.py", line 105, in <module>
    found_group=findgroup(gitlab_namespace)
  File "lib/manage_gitlab_project.py", line 54, in findgroup
    while len(git.groups(page=page)) > 0:
  File "/usr/lib/python2.6/site-packages/gitlab3/__init__.py", line 76, in fn
    objs = parent._get(api._uq_url, data=data)
  File "/usr/lib/python2.6/site-packages/gitlab3/__init__.py", line 415, in _get
    return self._request(requests.get, api_url, addl_keys, data)
  File "/usr/lib/python2.6/site-packages/gitlab3/__init__.py", line 435, in _request
    self._check_status_code(r.status_code, url, data)
  File "/usr/lib/python2.6/site-packages/gitlab3/__init__.py", line 411, in _check_status_code
    raise self._code_to_exc[status_code](msg)
gitlab3.exceptions.UnauthorizedRequest: URL: https://gitlab.com/api/v3/groups, Data: {'page': 1}

**Comment by logicminds** [comment]
fixed in #78
