### ISSUE TITLE
Can't create first mirror?

### ISSUE THREAD

**Issue by dankegel** [samrocketman/gitlab-mirrors#82]
I'm on Ubuntu 14.04 (as ubuntu 12.04's requests was too old), with gitlab 7.11.4-ee.
The mirrors group already exists, and is empty.  
Creating my first mirror fails like this:

$ ./add_mirror.sh --git --project-name zarg --mirror git.blarg.com:/git/repo/zarg
Resolving gitlab remote.
Traceback (most recent call last):
  File "lib/manage_gitlab_project.py", line 109, in <module>
    found_project=createproject(project_name)
  File "lib/manage_gitlab_project.py", line 98, in createproject
    new_project=git.group(found_group.id).transfer_project(new_project.id)
  File "build/bdist.linux-x86_64/egg/gitlab3/__init__.py", line 248, in fn
  File "build/bdist.linux-x86_64/egg/gitlab3/__init__.py", line 418, in _post
  File "build/bdist.linux-x86_64/egg/gitlab3/__init__.py", line 435, in _request
  File "build/bdist.linux-x86_64/egg/gitlab3/__init__.py", line 411, in _check_status_code
gitlab3.exceptions.ForbiddenRequest: URL: https://gitlab.blarg.com/api/v3/groups/74/projects/254, Data: {}

Creating the group manually via the gitlab interface and then repeating that command seems to work around the problem.

**Comment by logicminds** [comment]
The group needs to exist first and then assign the gitmirror user owner of the group.

**Comment by samrocketman** [comment]
Currently group creation in normal and intended to be sure the user wishes to mirror to said group.

**Comment by samrocketman** [comment]
This may change at a later date with #73.
